version: '3.8'

services:
  app:
    build: .
    ports:
      - "4300:4300"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/survivor
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: